const SET_LOADING_TRUE ='SET_LOADING_TRUE'
const CONCAT_NEW_USER  = 'CONCAT_NEW_USER'
const GET_USERS ='GET_USERS'
const GET_ERRORS = 'GET_ERRORS'
const UPDATE_USER = 'UPDATE_USER'
const DELETE_USER ='DELETE_USER'
const GET_IMAGES ='GET_IMAGES'
const CONCAT_IMAGE ='CONCAT_IMAGE'
const DELETE_IMAGE ='DELETE_IMAGE'
 
 
export {
    SET_LOADING_TRUE,
    CONCAT_NEW_USER,
    GET_USERS ,
    GET_ERRORS,
    UPDATE_USER,
    DELETE_USER,
    GET_IMAGES ,
    CONCAT_IMAGE ,
     DELETE_IMAGE
}